Rentar.MVC/Controllers/TipoCombustiblesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RentCar.Data;
using RentCar.Model;

namespace Rentar.MVC.Controllers
{
    public class TipoCombustiblesController : Controller
    {
        private RentCarEntities db = new RentCarEntities();

        // GET: TipoCombustibles
        public ActionResult Index()
        {
            return View(db.TipoCombustibles.ToList());
        }

        // GET: TipoCombustibles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoCombustible tipoCombustible = db.TipoCombustibles.Find(id);
            if (tipoCombustible == null)
            {
                return HttpNotFound();
            }
            return View(tipoCombustible);
        }

        // GET: TipoCombustibles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoCombustibles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdTipoCombustible,Descripcion,Estado")] TipoCombustible tipoCombustible)
        {
            if (ModelState.IsValid)
            {
                db.TipoCombustibles.Add(tipoCombustible);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipoCombustible);
        }

        // GET: TipoCombustibles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoCombustible tipoCombustible = db.TipoCombustibles.Find(id);
            if (tipoCombustible == null)
            {
                return HttpNotFound();
            }
            return View(tipoCombustible);
        }

        // POST: TipoCombustibles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdTipoCombustible,Descripcion,Estado")] TipoCombustible tipoCombustible)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoCombustible).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipoCombustible);
        }

        // GET: TipoCombustibles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoCombustible tipoCombustible = db.TipoCombustibles.Find(id);
            if (tipoCombustible == null)
            {
                return HttpNotFound();
            }
            return View(tipoCombustible);
        }

        // POST: TipoCombustibles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TipoCombustible tipoCombustible = db.TipoCombustibles.Find(id);
            db.TipoCombustibles.Remove(tipoCombustible);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentar.MVC/Controllers/TipoVehiculoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RentCar.Data;
using RentCar.Model;

namespace Rentar.MVC.Controllers
{
    public class TipoVehiculoesController : Controller
    {
        private RentCarEntities db = new RentCarEntities();

        // GET: TipoVehiculoes
        public ActionResult Index()
        {
            return View(db.TipoVehiculos.ToList());
        }

        // GET: TipoVehiculoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoVehiculo tipoVehiculo = db.TipoVehiculos.Find(id);
            if (tipoVehiculo == null)
            {
                return HttpNotFound();
            }
            return View(tipoVehiculo);
        }

        // GET: TipoVehiculoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoVehiculoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdTipoVehiculo,Descripcion,Estado")] TipoVehiculo tipoVehiculo)
        {
            if (ModelState.IsValid)
            {
                db.TipoVehiculos.Add(tipoVehiculo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipoVehiculo);
        }

        // GET: TipoVehiculoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoVehiculo tipoVehiculo = db.TipoVehiculos.Find(id);
            if (tipoVehiculo == null)
            {
                return HttpNotFound();
            }
            return View(tipoVehiculo);
        }

        // POST: TipoVehiculoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdTipoVehiculo,Descripcion,Estado")] TipoVehiculo tipoVehiculo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoVehiculo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipoVehiculo);
        }

        // GET: TipoVehiculoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoVehiculo tipoVehiculo = db.TipoVehiculos.Find(id);
            if (tipoVehiculo == null)
            {
                return HttpNotFound();
            }
            return View(tipoVehiculo);
        }

        // POST: TipoVehiculoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TipoVehiculo tipoVehiculo = db.TipoVehiculos.Find(id);
            db.TipoVehiculos.Remove(tipoVehiculo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentar.MVC/Controllers/VehiculoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RentCar.Data;
using RentCar.Model;

namespace Rentar.MVC.Controllers
{
    public class VehiculoesController : Controller
    {
        private RentCarEntities db = new RentCarEntities();

        // GET: Vehiculoes
        public ActionResult Index()
        {
            var vehiculos = db.Vehiculos.Include(v => v.Modelo).Include(v => v.TipoCombustible).Include(v => v.TipoVehiculo);
            return View(vehiculos.ToList());
        }

        // GET: Vehiculoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.Vehiculos.Find(id);
            if (vehiculo == null)
            {
                return HttpNotFound();
            }
            return View(vehiculo);
        }

        // GET: Vehiculoes/Create
        public ActionResult Create()
        {
            ViewBag.IdModelo = new SelectList(db.Modelos, "IdModelo", "Descripcion");
            ViewBag.IdTipoCombustible = new SelectList(db.TipoCombustibles, "IdTipoCombustible", "Descripcion");
            ViewBag.IdTipoVehiculo = new SelectList(db.TipoVehiculos, "IdTipoVehiculo", "Descripcion");
            return View();
        }

        // POST: Vehiculoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdVehiculo,Descripcion,NoChasis,NoMotor,NoPlaca,IdTipoVehiculo,IdModelo,IdTipoCombustible,Estado")] Vehiculo vehiculo)
        {
            if (ModelState.IsValid)
            {
                db.Vehiculos.Add(vehiculo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdModelo = new SelectList(db.Modelos, "IdModelo", "Descripcion", vehiculo.IdModelo);
            ViewBag.IdTipoCombustible = new SelectList(db.TipoCombustibles, "IdTipoCombustible", "Descripcion", vehiculo.IdTipoCombustible);
            ViewBag.IdTipoVehiculo = new SelectList(db.TipoVehiculos, "IdTipoVehiculo", "Descripcion", vehiculo.IdTipoVehiculo);
            return View(vehiculo);
        }

        // GET: Vehiculoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.Vehiculos.Find(id);
            if (vehiculo == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdModelo = new SelectList(db.Modelos, "IdModelo", "Descripcion", vehiculo.IdModelo);
            ViewBag.IdTipoCombustible = new SelectList(db.TipoCombustibles, "IdTipoCombustible", "Descripcion", vehiculo.IdTipoCombustible);
            ViewBag.IdTipoVehiculo = new SelectList(db.TipoVehiculos, "IdTipoVehiculo", "Descripcion", vehiculo.IdTipoVehiculo);
            return View(vehiculo);
        }

        // POST: Vehiculoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdVehiculo,Descripcion,NoChasis,NoMotor,NoPlaca,IdTipoVehiculo,IdModelo,IdTipoCombustible,Estado")] Vehiculo vehiculo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehiculo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdModelo = new SelectList(db.Modelos, "IdModelo", "Descripcion", vehiculo.IdModelo);
            ViewBag.IdTipoCombustible = new SelectList(db.TipoCombustibles, "IdTipoCombustible", "Descripcion", vehiculo.IdTipoCombustible);
            ViewBag.IdTipoVehiculo = new SelectList(db.TipoVehiculos, "IdTipoVehiculo", "Descripcion", vehiculo.IdTipoVehiculo);
            return View(vehiculo);
        }

        // GET: Vehiculoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.Vehiculos.Find(id);
            if (vehiculo == null)
            {
                return HttpNotFound();
            }
            return View(vehiculo);
        }

        // POST: Vehiculoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehiculo vehiculo = db.Vehiculos.Find(id);
            db.Vehiculos.Remove(vehiculo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentar.MVC/Views/Vehiculoes/Create.cshtml
@model RentCar.Model.Vehiculo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehiculo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoChasis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoChasis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoChasis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoMotor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoMotor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoMotor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoPlaca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoPlaca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoPlaca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoVehiculo, "IdTipoVehiculo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoVehiculo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoVehiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdModelo, "IdModelo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdModelo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdModelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoCombustible, "IdTipoCombustible", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoCombustible", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoCombustible, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rentar.MVC/Views/Vehiculoes/Delete.cshtml
@model RentCar.Model.Vehiculo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehiculo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Modelo.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoCombustible.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCombustible.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoVehiculo.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoVehiculo.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoChasis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoChasis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoMotor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoMotor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoPlaca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoPlaca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Rentar.MVC/Views/Vehiculoes/Details.cshtml
@model RentCar.Model.Vehiculo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vehiculo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Modelo.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoCombustible.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCombustible.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoVehiculo.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoVehiculo.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoChasis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoChasis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoMotor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoMotor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoPlaca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoPlaca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdVehiculo }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Rentar.MVC/Views/Vehiculoes/Index.cshtml
@model IEnumerable<RentCar.Model.Vehiculo>

@{
    ViewBag.Title = "Vehiculos";
}

<h2>Vehiculos</h2>

<p>
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Create New", "Create")
            </th>
            <th>
                @Html.ActionLink("Marcas", "Index", "Marcas")
            </th>
            <th>
                @Html.ActionLink("Tipo Combustible", "Index", "TipoCombustibles")
            </th>
            <th>
                @Html.ActionLink("Tipo Vehiculo", "Index", "TipoVehiculoes")
            </th>
            <th>
                @Html.ActionLink("Volver Al Home", "Index", "Home")
            </th>
        </tr>
    </table>




</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Modelo.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoCombustible.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoVehiculo.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoChasis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoMotor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoPlaca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoCombustible.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoVehiculo.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoChasis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoMotor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoPlaca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.IdVehiculo }) |
                @Html.ActionLink("Details", "Details", new { id = item.IdVehiculo }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.IdVehiculo })
            </td>
        </tr>
    }

</table>





<label style="background: #008bd6;height:3px;width:5%;display:block;margin:20px auto;"></label>
<section style="width: 100%;margin: auto;margin-bottom: 50px;">
    <div style="width: 33.333%;float: left;padding: 20px 20px;box-sizing: border-box;margin: auto;text-align: justify;">
        <h4 style="padding-bottom: 20px">Kia K5</h4>
        <div style="background-image:url(../../Imagenes/kiak5.jpg);background-repeat: no-repeat; background-position:center; background-attachment:scroll;background-size:contain;width:30%">
            <br /><br />.<br />
        </div>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio facere unde natus cumque, rem sed recusandae voluptates error. Quibusdam quaerat distinctio eligendi, vero quos doloribus. Doloribus adipisci praesentium perspiciatis eius? </p>
    </div>
    <div style="width: 33.333%;float: left;padding: 20px 20px;box-sizing: border-box;margin: auto;text-align: justify;">
        <h4 style="padding-bottom: 20px">Hyundai N20 </h4>
        <div style="background-image:url(../../Imagenes/hyundai.png);background-repeat: no-repeat; background-position:center; background-attachment:scroll;background-size:contain;width:25%">
            <br /><br />.<br />
        </div>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio facere unde natus cumque, rem sed recusandae voluptates error. Quibusdam quaerat distinctio eligendi, vero quos doloribus. Doloribus adipisci praesentium perspiciatis eius? </p>
    </div>
    <div style="width: 33.333%;float: left;padding: 20px 20px;box-sizing: border-box;margin: auto;text-align: justify;">
        <h4 style="padding-bottom: 20px">Kia Sorento</h4>
        <div style="background-image:url(../../Imagenes/sorento.png);background-repeat: no-repeat; background-position:center; background-attachment:scroll;background-size:contain;width:30%">
            <br /><br />.<br />
        </div>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio facere unde natus cumque, rem sed recusandae voluptates error. Quibusdam quaerat distinctio eligendi, vero quos doloribus. Doloribus adipisci praesentium perspiciatis eius? </p>
    </div>
</section>

<section style="margin-top:50px; background:url(../../Imagenes/1a.jpg);float:left;width:100%;height:200%;background-repeat:no-repeat;background-size:cover;background-attachment:fixed;text-align:center; background-position:center;color:white">
    <br />.<br />
    <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit.<a href="http://www.google.com">Link</a></h3>
    <br />.<br />

</section>

<section style="width: 100%;margin: auto;margin-bottom: 50px;">
    <div style="width: 33.333%;float: left;padding: 20px 20px;box-sizing: border-box;margin: auto;text-align: justify;">
        <h4 style="padding-bottom: 20px">Isuzu Dimax</h4>
        <div style="background-image:url(../../Imagenes/isuzu.jpg);background-repeat: no-repeat; background-position:center; background-attachment:scroll;background-size:contain;width:30%">
            <br /><br />.<br />
        </div>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio facere unde natus cumque, rem sed recusandae voluptates error. Quibusdam quaerat distinctio eligendi, vero quos doloribus. Doloribus adipisci praesentium perspiciatis eius? </p>
    </div>
    <div style="width: 33.333%;float: left;padding: 20px 20px;box-sizing: border-box;margin: auto;text-align: justify;">
        <h4 style="padding-bottom: 20px">Toyota Corola</h4>
        <div style="background-image:url(../../Imagenes/corola.jpg);background-repeat: no-repeat; background-position:center; background-attachment:scroll;background-size:contain;width:30%">
            <br /><br />.<br />
        </div>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio facere unde natus cumque, rem sed recusandae voluptates error. Quibusdam quaerat distinctio eligendi, vero quos doloribus. Doloribus adipisci praesentium perspiciatis eius? </p>
    </div>
    <div style="width: 33.333%;float: left;padding: 20px 20px;box-sizing: border-box;margin: auto;text-align: justify;">
        <h4 style="padding-bottom: 20px">Toyota Hilux</h4>
        <div style="background-image:url(../../Imagenes/hilux2.jpg);background-repeat: no-repeat; background-position:center; background-attachment:scroll;background-size:contain;width:25%">
            <br /><br />.<br />
        </div>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio facere unde natus cumque, rem sed recusandae voluptates error. Quibusdam quaerat distinctio eligendi, vero quos doloribus. Doloribus adipisci praesentium perspiciatis eius? </p>
    </div>
</section>